#!/usr/bin/env node
// Reads data/products.json and writes idempotent D1 insert SQL to worker/seed.sql (or a path given as argv[2]).
// Each row must carry drink + material (the classifier's inputs); the stored class is recomputed here from rules.js
// and any row the rules call `unknown` is skipped, never stored. Usage:
//   node worker/seed.mjs [data/products.json] [worker/seed.sql]
//   wrangler d1 execute return-rate --local --file=worker/seed.sql
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { classify } from './src/rules.js';

const here = dirname(fileURLToPath(import.meta.url));
const inPath = resolve(process.argv[2] || resolve(here, '../data/products.json'));
const outPath = resolve(process.argv[3] || resolve(here, 'seed.sql'));

const q = (v) => (v == null ? 'NULL' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);

export function buildSql(rows) {
  const lines = ['-- generated by worker/seed.mjs; safe to re-run'];
  let kept = 0, skipped = [];
  for (const r of rows) {
    const upc = String(r.upc ?? '').trim();
    if (!/^(\d{8}|\d{12}|\d{13})$/.test(upc) || !r.name || !r.drink || !r.material) { skipped.push(upc || '(no upc)'); continue; }
    const size = r.size_ml == null ? null : Number(r.size_ml);
    const refillable = r.refillable === true ? 1 : 0;
    const c = classify({ drink: r.drink, material: r.material, size_ml: size, refillable: !!refillable });
    if (c.class === 'unknown') { skipped.push(upc); continue; }
    lines.push(
      `INSERT INTO items (upc, name, brand, size_ml, drink, material, refillable, class, source, edited_by) VALUES (` +
      [q(upc), q(r.name), q(r.brand ?? null), q(Number.isFinite(size) ? size : null), q(r.drink), q(r.material),
        String(refillable), q(c.class), q(r.source ?? 'openfoodfacts'), q('seed')].join(', ') +
      `) ON CONFLICT(upc) DO UPDATE SET name=excluded.name, brand=excluded.brand, size_ml=excluded.size_ml, ` +
      `drink=excluded.drink, material=excluded.material, refillable=excluded.refillable, class=excluded.class, ` +
      `source=excluded.source WHERE items.source <> 'counter';`,
    );
    kept++;
  }
  return { sql: lines.join('\n') + '\n', kept, skipped };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const rows = JSON.parse(readFileSync(inPath, 'utf8'));
  const { sql, kept, skipped } = buildSql(Array.isArray(rows) ? rows : rows.products || []);
  writeFileSync(outPath, sql);
  console.log(`wrote ${outPath}: ${kept} items, ${skipped.length} skipped${skipped.length ? ' (' + skipped.slice(0, 5).join(', ') + (skipped.length > 5 ? ', …' : '') + ')' : ''}`);
}
